#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Copyright (c) 2022 Intel Corporation.

source .env

START_TIME=""
SUMMRY_LOG=""
TESTS_CLIENT="tests-client"
TESTS_SERVER="tests-server"
TEST_FILES=""
SUB_FOLDERS=""
TEST_LIST_FILE="/tmp/tests"
OLD_IFS=""

usage() {
  cat << _EOF
Usage: ${0##*/} [-f CMDFILES] [-c CMDLINE] [-o LOGFILE]
  -f CMDFILES   execute user defined list of tests in files separated by ','
  -c CMDLINE    execute test case
  -o LOGFILE    redirect output of tests to file

Examples:
  ./runtests -f cet/tests
  ./runtests -f cet/tests -o cet_tests.log
  ./runtests -f tests-client  // exeucte tests-client/tests for all subfolders
  ./runtests -f tests-server  // exeucte tests-server/tests for all subfolders
  ./runtests -c ./cet/quick_test -o cet_quick_test.log
_EOF
}

err() {
  echo -e "\n$*" >&2
  exit 1
}

runtest() {
  local cmdline=$1
  local logfile=$2
  local subfolder=$3
  local start
  local stop
  local duration
  local code
  local result
  local case_result=""

  if [[ -n "$logfile" ]]; then
    echo "<<<test start - '$cmdline'>>" | tee -a "$logfile"
  else
    echo "<<<test start - '$cmdline'>>"
  fi

  if [[ -z "$subfolder" ]]; then
    echo "LKVS tests: $cmdline" >> /dev/kmsg
  else
    echo "LKVS tests: ${subfolder}/${cmdline}" >> /dev/kmsg
  fi

  set -o pipefail
  start=$(date +%s.%3N)

  if [[ -n "$logfile" ]]; then
    eval "$cmdline |& tee -a $logfile" &
  else
    eval "$cmdline" &
  fi

  wait $!
  code=$?

  stop=$(date +%s.%3N)
  duration=$(printf '%.3f' "$(bc <<< "$stop-$start")")
  set +o pipefail

  case $code in
    0)
      result="PASS"
      ;;
    2)
      result="BLOCK"
      ;;
    32)
      result="NA"
      ;;
    *)
      result="FAIL"
      ;;
  esac

  if [[ -n "$logfile" ]]; then
    echo -e "<<<test end, result: $result, duration: $duration>>\n" | tee -a "$logfile"
  else
    echo -e "<<<test end, result: $result, duration: ${duration}s>>\n"
  fi
  case_result=$(printf "[RESULT]%-68s%-11s%-12s%-8s" "[$cmdline]" " [$result]" "[$code]" "[${duration}s]")
  echo "$case_result" >> "$SUMMRY_LOG"
}

runcmdfile() {
  local cmdfile=$1
  local logfile=$2
  local subfolder=""
  local file_type=""
  local lines=""
  local line=""

  if [[ "$cmdfile" == *"/"* ]]; then
    subfolder=${cmdfile%/*}
  else
    echo "cmdfile:$cmdfile(no '/') is not in a subfolder!"
  fi

  grep -v "^#.*" "$cmdfile" | grep -v "^$" > "$TEST_LIST_FILE"
  lines=$(cat $TEST_LIST_FILE)
  OLD_IFS="$IFS"
  IFS=$'\n'
  for line in $lines; do
    runtest "$line" "$logfile" "$subfolder"
  done
  IFS="$OLD_IFS"
}

prepare_files_list() {
  local test_file_type=$1
  local sub_folder=""

  for sub_folder in $SUB_FOLDERS; do
    # Remov the / in the end
    sub_folder="${sub_folder%/}"
    [[ "$sub_folder" == "common" ]] && continue

    if [[ -e "${sub_folder}/${test_file_type}" ]]; then
      if [[ -z "$TEST_FILES" ]]; then
        TEST_FILES="${sub_folder}/${test_file_type}"
      else
        TEST_FILES="${TEST_FILES},${sub_folder}/${test_file_type}"
      fi
    elif [[ -e "${sub_folder}/tests" ]]; then
      if [[ -z "$TEST_FILES" ]]; then
        TEST_FILES="${sub_folder}/tests"
      else
        TEST_FILES="${TEST_FILES},${sub_folder}/tests"
      fi
    else
      echo "WARNING: No $test_file_type or tests file under $sub_folder folder."
    fi
  done
}

test_all() {
  local test_file_type=$1

  # Don't quote */, otherwise it could not list all folders.
  SUB_FOLDERS=$(ls -1 -d */)

  prepare_files_list "$test_file_type"
  CMDFILES="$TEST_FILES"
  if [[ -z "$LOGFILE" ]]; then
    echo "Test files: $CMDFILES"
  else
    echo "Test files: $CMDFILES" | tee "$LOGFILE"
  fi
}

# Default value
: "${LOGFILE:="./lkvs.log"}"
: CMDFILES=""
: CMDLINE=""

while getopts ":o:f:c:h" opt; do
  case "$opt" in
    o)
      LOGFILE=$OPTARG
      ;;
    f)
      CMDFILES=$OPTARG
      [[ "$CMDFILES" == "$TESTS_CLIENT" ]] && test_all "$TESTS_CLIENT"
      [[ "$CMDFILES" == "$TESTS_SERVER" ]] && test_all "$TESTS_SERVER"
      ;;
    c)
      CMDLINE=$OPTARG
      ;;
    h)
      usage
      exit 0
      ;;
    \?)
      usage
      err "Invalid option: -$OPTARG"
      ;;
    :)
      usage
      err "Option -$OPTARG requires an argument."
      ;;
  esac
done

if [[ -z "$CMDFILES" ]] && [[ -z "$CMDLINE" ]]; then
  usage
  err "no test to run!"
fi

START_TIME="$(date +%Y-%m-%d_%H-%M-%S)"
SUMMRY_LOG="/tmp/lkvs_${START_TIME}_summary.log"
echo "Test Start Time: $START_TIME" > "$SUMMRY_LOG"
{
  echo "--------------------------------------------------------"
  printf "%-76s%-11s%-12s%-8s\n" "Testcase" "Result" "Exit Value" "Duration"
  printf "%-76s%-11s%-12s%-8s\n" "--------" "------" "----------" "--------"
} >> "$SUMMRY_LOG"

for cmdfile in $(tr "," " " <<< "$CMDFILES"); do
  if [[ ! -f "$cmdfile" ]]; then
    echo "WARNING: $cmdfile not found!"
    continue
  fi

  [[ $(which file) ]] && {
    file_type=""
    file_type=$(file "$cmdfile")
    [[ "$file_type" == *"text"* ]] || {
      echo "WARNING: -f $cmdfile is not a text type file, it's real type:|$file_type|"
      echo "Please choose the correct tests file."
      usage
      continue
    }
  }

  runcmdfile "$cmdfile" "$LOGFILE"
done

if [[ -n "$CMDLINE" ]]; then
  runtest "$CMDLINE" "$LOGFILE"
fi

# Add the following print for the end of the case summary.
echo "--------------------------------------------------------" >> "$SUMMRY_LOG"

[[ -z "$LOGFILE" ]] || cat "$SUMMRY_LOG" >> "$LOGFILE"
cat "$SUMMRY_LOG"
